

name: 'media'

services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    restart: always
    environment:
      - TZ=America/Sao_Paulo
      - WEBUI_PORT=8080
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/servo/Services/qbittorrent/config:/config
      - /mnt/satassd/plex_home_server_files/Downloads/torrents:/downloads
    ports:
      - '8080:8080'
      - '62609:62609'

  bazarr:
    image: ghcr.io/linuxserver/bazarr:latest
    restart: always
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/satassd/plex_home_server_files/Videos/radarr:/movies
      - /mnt/satassd/plex_home_server_files/Videos/sonarr:/tv
      - /home/servo/Services/bazarr/appdata/config:/config
    ports:
      - '6767:6767'

  prowlarr:
    image: ghcr.io/hotio/prowlarr:latest
    restart: always
    depends_on:
      - flaresolverr
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/servo/Services/prowlarr/config:/config
    ports:
      - '9696:9696'

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: always
    volumes:
      - /home/servo/Services/flaresolverr/config:/config
    ports:
      - '8191:8191'

  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    restart: always
    depends_on:
      - qbittorrent
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/servo/Services/radarr/appdata/config:/config
      - /mnt/satassd/plex_home_server_files/Downloads/torrents:/downloads
      - /mnt/satassd/plex_home_server_files/Videos/radarr/movies:/movies
      - /mnt/satassd/plex_home_server_files/Videos/radarr/anime:/anime
    ports:
      - '7878:7878'

  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    restart: always
    depends_on:
      - qbittorrent
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/servo/Services/sonarr/appdata/config:/config
      - /mnt/satassd/plex_home_server_files/Videos/sonarr:/tv
      - /mnt/satassd/plex_home_server_files/Downloads/torrents:/downloads
    ports:
      - '8989:8989'

  plex:
    image: plexinc/pms-docker:latest
    restart: always
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
      - VA_DRIVER=IHD
      - PLEX_HW_TRANS_MAX=16
    volumes:
      - /home/servo/Services/plex/config:/config
      - /home/servo/Services/plex/data:/data
      - /home/servo/Services/plex/transcode:/transcode
      - /mnt/satassd/plex_home_server_files/Videos:/media
    devices:
      - /dev/dri:/dev/dri
      - /dev/bus/usb:/dev/bus/usb
    network_mode: host
