version: '3'

name: 'rip'

services:
  makemkv:
    image: jlesage/makemkv
    restart: unless-stopped
    volumes:
      - /home/servo/makemkv:/config
      - /mnt/satassd/plex_home_server_files/Videos/BluRay:/output
      - /home/servo:/storage:ro
    devices:
      - /dev/sr0:/dev/sr0
      - /dev/sg0:/dev/sg0
    ports:
      - '5800:5800'

  handbrake:
    restart: unless-stopped
    image: jlesage/handbrake
    ports:
      - "5801:5800"
    environment:
      - AUTOMATED_CONVERSION=0
      - HANDBRAKE_GUI=1
      - DARK_MODE=1
      - TZ=America/Sao_Paulo
    volumes:
      - "/home/servo/handbrake:/config:rw"
      - "/home/servo:/storage:ro"
      - "/mnt/satassd/plex_home_server_files/Videos/BluRay:/watch:rw"
      - "/mnt/satassd/plex_home_server_files/Videos/BluRayOptimized:/output:rw"
    devices:
      - /dev/dri:/dev/dri
